### ISSUE TITLE
Find a way to keep the "table" view toggled when refreshing the page from table view (Deleting/editing info)

### ISSUE THREAD

**Issue by 1alyciaoliveira** [1alyciaoliveira/JobJourney#114]
Currently, when deleting a job post we use window reload function, but the page goes back to board view.

**Comment by Maelikah** [comment]
This has been fixed. the problem was we were not using localstorage to store the current view. some changed were added in dashboard.js and viewbutton.js after that, it now works as expected.

**Comment by Maelikah** [comment]
Change merged
