### ISSUE TITLE
Create edit user mutation for back and front

### ISSUE THREAD

**Issue by 1alyciaoliveira** [1alyciaoliveira/JobJourney#45]

**Comment by MariaFernandaMarroquin** [comment]
updatePassword on back is working. 
<img width="935" alt="Captura de Pantalla 2023-08-19 a la(s) 17 13 48" src="https://github.com/1alyciaoliveira/JobJourney/assets/126350197/b4fe348a-a84c-45c4-967a-81f8b9fd5040">

**Comment by MariaFernandaMarroquin** [comment]
Front worked by @AlexTrejo92 done! :)
