### ISSUE TITLE
Create logic to edit user password

### ISSUE THREAD

**Issue by Maelikah** [1alyciaoliveira/JobJourney#76]
When the update button is clicked inside the edit profile component
the values of username, email and password can be changed  in the DB

**Comment by AlexTrejo92** [comment]
Basic structure for the code to handle the EditPassword mutation done. Will review the information with the backend code that will be merged and test with that.

**Comment by AlexTrejo92** [comment]
The user can now change it's password, and includes a validation so that it cannot be the same password as before. Right now only shows a warning on the console and wont let you submit, but an alert on the front will be shown in this case.
